import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/app/component/Navbar'
import Footer from '@/app/component/Footer'
import { ContextProvider } from '@/app/component/Context'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ContextProvider>
    <html lang="en">
      <body className={inter.className}>
      {children }
      </body>
     
    </html>
    </ContextProvider>
  ) 
}
